# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import copier_pb2 as copier__pb2
except ImportError:
    import copier_pb2 as copier__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in copier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CopierServiceStub:
    """Trade copier operations over gRPC.

    Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
    preventing plain-text credential leakage in HTTP query parameters, server access logs,
    or proxy routing histories.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/copier.CopierService/Start',
                request_serializer=copier__pb2.StartRequest.SerializeToString,
                response_deserializer=copier__pb2.StartReply.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/copier.CopierService/List',
                request_serializer=copier__pb2.ListRequest.SerializeToString,
                response_deserializer=copier__pb2.ListReply.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/copier.CopierService/Pause',
                request_serializer=copier__pb2.PauseRequest.SerializeToString,
                response_deserializer=copier__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/copier.CopierService/Remove',
                request_serializer=copier__pb2.RemoveRequest.SerializeToString,
                response_deserializer=copier__pb2.SimpleReply.FromString,
                _registered_method=True)


class CopierServiceServicer:
    """Trade copier operations over gRPC.

    Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
    preventing plain-text credential leakage in HTTP query parameters, server access logs,
    or proxy routing histories.
    """

    def Start(self, request, context):
        """Start a trade copier between master and slave accounts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """List all active and paused copiers belonging to a user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Pause or resume an existing copier without deleting configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Remove a copier and unregister trade hooks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=copier__pb2.StartRequest.FromString,
                    response_serializer=copier__pb2.StartReply.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=copier__pb2.ListRequest.FromString,
                    response_serializer=copier__pb2.ListReply.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=copier__pb2.PauseRequest.FromString,
                    response_serializer=copier__pb2.SimpleReply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=copier__pb2.RemoveRequest.FromString,
                    response_serializer=copier__pb2.SimpleReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'copier.CopierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('copier.CopierService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CopierService:
    """Trade copier operations over gRPC.

    Credentials (passwords) are strictly carried in the request body over HTTP/2 gRPC,
    preventing plain-text credential leakage in HTTP query parameters, server access logs,
    or proxy routing histories.
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Start',
            copier__pb2.StartRequest.SerializeToString,
            copier__pb2.StartReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/List',
            copier__pb2.ListRequest.SerializeToString,
            copier__pb2.ListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Pause',
            copier__pb2.PauseRequest.SerializeToString,
            copier__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Remove',
            copier__pb2.RemoveRequest.SerializeToString,
            copier__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DemoAccountStub:
    """Demo account creation service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenDemoAccount = channel.unary_unary(
                '/copier.DemoAccount/OpenDemoAccount',
                request_serializer=copier__pb2.GuiDemoOpenAccountRequest.SerializeToString,
                response_deserializer=copier__pb2.GuiDemoOpenAccountReply.FromString,
                _registered_method=True)


class DemoAccountServicer:
    """Demo account creation service definition
    """

    def OpenDemoAccount(self, request, context):
        """Provision a new MetaTrader demo account on the fly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoAccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenDemoAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDemoAccount,
                    request_deserializer=copier__pb2.GuiDemoOpenAccountRequest.FromString,
                    response_serializer=copier__pb2.GuiDemoOpenAccountReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'copier.DemoAccount', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('copier.DemoAccount', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DemoAccount:
    """Demo account creation service definition
    """

    @staticmethod
    def OpenDemoAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.DemoAccount/OpenDemoAccount',
            copier__pb2.GuiDemoOpenAccountRequest.SerializeToString,
            copier__pb2.GuiDemoOpenAccountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
