# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import copier_pb2 as copier__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in copier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CopierServiceStub:
    """Trade copier operations over gRPC.

    This exists for one reason: the REST equivalents take the master's and slave's MT account
    PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    between, and to the browser's history — so every copier ever started has put two sets of live
    trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    where nothing on the path records them.

    The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    the same operations, not a replacement, and it delegates to exactly the same implementation so
    the two cannot drift.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/copier.CopierService/Start',
                request_serializer=copier__pb2.StartRequest.SerializeToString,
                response_deserializer=copier__pb2.StartReply.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/copier.CopierService/List',
                request_serializer=copier__pb2.ListRequest.SerializeToString,
                response_deserializer=copier__pb2.ListReply.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/copier.CopierService/Pause',
                request_serializer=copier__pb2.PauseRequest.SerializeToString,
                response_deserializer=copier__pb2.SimpleReply.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/copier.CopierService/Remove',
                request_serializer=copier__pb2.RemoveRequest.SerializeToString,
                response_deserializer=copier__pb2.SimpleReply.FromString,
                _registered_method=True)


class CopierServiceServicer:
    """Trade copier operations over gRPC.

    This exists for one reason: the REST equivalents take the master's and slave's MT account
    PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    between, and to the browser's history — so every copier ever started has put two sets of live
    trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    where nothing on the path records them.

    The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    the same operations, not a replacement, and it delegates to exactly the same implementation so
    the two cannot drift.
    """

    def Start(self, request, context):
        """Start a copier. The only call that carries credentials.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Every copier belonging to a user. Never returns stored passwords — see CopierSummary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Pause or resume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Remove a copier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=copier__pb2.StartRequest.FromString,
                    response_serializer=copier__pb2.StartReply.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=copier__pb2.ListRequest.FromString,
                    response_serializer=copier__pb2.ListReply.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=copier__pb2.PauseRequest.FromString,
                    response_serializer=copier__pb2.SimpleReply.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=copier__pb2.RemoveRequest.FromString,
                    response_serializer=copier__pb2.SimpleReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'copier.CopierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('copier.CopierService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CopierService:
    """Trade copier operations over gRPC.

    This exists for one reason: the REST equivalents take the master's and slave's MT account
    PASSWORDS as query parameters. A query string is written to the ingress log, to any proxy in
    between, and to the browser's history — so every copier ever started has put two sets of live
    trading credentials into plain-text logs. gRPC carries them in the request body over HTTP/2,
    where nothing on the path records them.

    The REST endpoints are untouched and still serve copyfront. This is an additional transport for
    the same operations, not a replacement, and it delegates to exactly the same implementation so
    the two cannot drift.
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Start',
            copier__pb2.StartRequest.SerializeToString,
            copier__pb2.StartReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/List',
            copier__pb2.ListRequest.SerializeToString,
            copier__pb2.ListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Pause',
            copier__pb2.PauseRequest.SerializeToString,
            copier__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copier.CopierService/Remove',
            copier__pb2.RemoveRequest.SerializeToString,
            copier__pb2.SimpleReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
